on:
  pull_request:
    branches:
      - main
jobs:
  merge_to_beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: staging
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin ${GITHUB_REF}
          git merge FETCH_HEAD
          git push
